export const  OWIDate = [
    {
        id:'1',
        owipage:'home, all',
        owiname:'Lagrotas Nanos',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'3.5',
        owiImage:'fur01.png',
        owieven:'cDown',

    },
    {
        id:'2',
        owipage:'home, all',
        owiname:'Caesar Salad',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'3.0',
        owiImage:'fur02.png',
        owieven:'cUp',

    },
    {
        id:'3',
        owipage:'home, all',
        owiname:'Pizza Mexicana',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'4.0',
        owiImage:'fur03.png',
        owieven:'cDown',
    },
    {
        id:'4',
        owipage:'home, all',
        owiname:'Lagrotas Nanos',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'3.5',
        owiImage:'fur01.png',
        owieven:'cDown',
    },
    {
        id:'5',
        owipage:'home, all',
        owiname:'Caesar Salad',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'3.0',
        owiImage:'fur02.png',
        owieven:'cUp',
    },
    {
        id:'6',
        owipage:'home, all',
        owiname:'Pizza Mexicana',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'4.0',
        owiImage:'fur03.png',
        owieven:'cDown',
    },
    {
        id:'7',
        owipage:'home, all',
        owiname:'Lagrotas Nanos',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'3.5',
        owiImage:'fur01.png',
        owieven:'cDown',
    },
    {
        id:'8',
        owipage:'home, all',
        owiname:'Caesar Salad',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'3.0',
        owiImage:'fur02.png',
        owieven:'cUp',
    },
    {
        id:'9',
        owipage:'home, all',
        owiname:'Pizza Mexicana',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'4.0',
        owiImage:'fur03.png',
        owieven:'cDown',
    },
    {
        id:'10',
        owipage:'home, all',
        owiname:'Lagrotas Nanos',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'3.5',
        owiImage:'fur01.png',
        owieven:'cDown',
    },
    {
        id:'11',
        owipage:'home, all',
        owiname:'Caesar Salad',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'3.0',
        owiImage:'fur02.png',
        owieven:'cUp',

    },
    {
        id:'12',
        owipage:'home, all',
        owiname:'Pizza Mexicana',
        owidisc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
        owiLinks:'gallary',
        owiRating:'4.0',
        owiImage:'fur03.png',
        owieven:'cDown',
    },
];


export const sImageDate = [
  {
    id:'1',
    ftitlename:'Furniture Wala in',
    ltitlename:'Indore',
    bIMage:'imageS1.png',
  },
  {
    id:'2',
    ftitlename:'Furniture Wala in',
    ltitlename:'Bhopal',
    bIMage:'imageS2.png',
  },
  {
    id:'3',
    ftitlename:'Furniture Wala in',
    ltitlename:'Ujjain',
    bIMage:'imageS3.png',
  },
];


export const FWDUMMYDATA = [
  {
    id:1,
    expyear :3,
    apage:'home, all',
    name:'Pavan Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',
  },
  {
    id:2,
    expyear :4,
    apage:'home, all',
    name:'Ajay Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',
  },
  {
    id:3,
    expyear :5,
    apage:'home, all',
    name:'Yash Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',
  },
  {
    id:4,
    expyear :6,
    apage:'all',
    name:'Ansh Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',
  },
  {
    id:5,
    expyear :7,
    apage:'home, all',
    name:'Rakesh Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',
  },
  {
    id:6,
    expyear :8,
    apage:'home, all',
    name:'Suresh Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',
  },
  {
    id:7,
    expyear :7,
    apage:'home, all',
    name:'Ansh Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',
  },
  {
    id:8,
    expyear :8,
    apage:'all',
    name:'Rakesh Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',

  },
  {
    id:9,
    expyear :9,
    apage:'all',
    name:'Suresh Carpenter',
    disc:'Lorem Ipsum is simply dummy text of the printing and typesetting',
    wahtsApp:'+917000913327',

  },
];

export  const sliderDate = [
    {
      id:'1',
      ftitlename:'Furniture Wala in',
      ltitlename:'Indore',
      disc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
      bIMage:'slider01.png',
    },
    {
      id:'2',
       ftitlename:'Furniture Wala in',
      ltitlename:'Bhopal',
      disc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
      bIMage:'slider01.png',
    },
    {
      id:'3',
      ftitlename:'Furniture Wala in',
      ltitlename:'Bhopal',
      disc:'Lorem ipsum dolor et, consectetur adipiscing elit, sed do eiusmod',
      bIMage:'slider01.png',
    },
  ];

export  const SosLinksdata = [
  {
      id:'1',
      fontFamaly:'faFont',
      name:'whatsapp',
      sosLinks:'https://www.whatsapp.com/',
  },
  {
      id:'2',
      fontFamaly:'faFont',
      name:'linkedin',
      sosLinks:'https://www.linkedin.com/',
  },
  {
      id:'3',
      fontFamaly:'faFont',
      name:'facebook',
      sosLinks:'https://www.facebook.com/',
  },
  {
      id:'4',
      fontFamaly:'faFont',
      name:'instagram',
      sosLinks:'https://www.instagram.com/',
  },
];